version: 2.1

orbs:
  win: circleci/windows@2.4.0
  heroku: circleci/heroku@1.2.3

jobs:
  build:
    working_directory: ~/Foxxit
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    
    steps:
      - checkout
      - run: dotnet build Foxxit/
      
  lint:
    executor:
      name: win/default
    
    steps:
      - checkout
      - run: dotnet tool update -g dotnet-format
      - run: dotnet format --check -v diag Foxxit/Foxxit.csproj
      - run: dotnet format --check -v diag XUnitTestsForFoxxit/XUnitTestsForFoxxit.csproj
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0

    steps:
      - checkout
      - run: dotnet test Foxxit/ -c Debug "--logger:Console;verbosity=normal" --diag:./Foxxit/test_log.txt

workflows:
  version: 2
  build_lint_test_heroku-deploy-only-develop:
    jobs:
      - build  
      - lint:
          requires:
            - build
      - test:
          requires:
            - lint
      - heroku/deploy-via-git:
          requires:
            - test
          filters:
            branches:
              only: 
                - develop